### PR TITLE
Allow OIDMSLogacyKRB5 if the mechtype is OIDKRB5

### PR DESCRIPTION
**Pull request by BryceDFisher**
This supports MS Server 2016, which still advertises the LegacyKRB5 OID.

### CODE REVIEW

**Comment by BryceDFisher** [comment]
I'm not sure why this didn't work with go1.12.  Everything passed...

**Comment by jcmturner** [comment]
relates to #278

**Comment by khilangudka** [comment]
I have been experiencing the problem in #278 and this change has fixed it for me. The version of go i am using is 1.12.2.

**Comment by BryceDFisher** [comment]
Wanted to revisit this

**Comment by jcmturner** [comment]
Thank you for this contribution. However I am closing this as PR #352 should address this as discussed in #278. Please let me know if it does not address the issue for you.

**Pull request closed without merging**
