### PR TITLE
Add support for raw KRB5 context tokens in spnego.SPNEGOKRB5Authenticate

### PR DESCRIPTION
**Pull request by jgiannuzzi**
This PR adds support for raw KRB5 context tokens in spnego.SPNEGOKRB5Authenticate.

Older versions of cURL, like the one packaged in CentOS 6 or even 7, send those tokens instead of proper SPNEGO context tokens. The WebSEAL reverse proxy, part of IBM Security Access Manager, also does that.

Supporting those tokens allows broader compatibility with those clients, and potentially others.

This PR should thus fix issue #278.

### CODE REVIEW

**Comment by jgiannuzzi** [comment]
Closed and reopened PR to trigger Travis CI to run the tests again.

**Comment by jgiannuzzi** [comment]
Closed and reopened PR to trigger Travis CI to run the tests again.

**Comment by jgiannuzzi** [comment]
Closed and reopened PR to trigger Travis CI to run the tests again.

**Comment by jgiannuzzi** [comment]
Rebased on latest master

**Comment by jgiannuzzi** [comment]
Hey @jcmturner, any comments about this?

**Comment by jgiannuzzi** [comment]
Rebased on latest master

**Comment by jcmturner** [comment]
@jgiannuzzi Thanks for the contribution. I have merged in an enhancement to address this under PR #366. This uses the approach you committed here but following a number of other changes it needed to go into a slightly different place in the code. Therefore I took your approach and adapted it to those changes. I have given you co-author credit on that given you provided this PR.

This will be released shortly as an enhancement to the new v8 major version. Thanks again!

**Comment by jgiannuzzi** [comment]
Thanks @jcmturner, much appreciated!

And congrats for the new v8 release!

**Pull request closed without merging**
