### PR TITLE
Add 19 missing error checks found by gometalinter

### PR DESCRIPTION
**Pull request by knweiss**
```
client/http.go:34:15:warning: ineffectual assignment to err (ineffassign)
gssapi/krb5Token.go:110:9:warning: ineffectual assignment to err (ineffassign)
messages/KDCReq.go:186:6:warning: ineffectual assignment to err (ineffassign)
messages/KDCReq.go:191:9:warning: ineffectual assignment to err (ineffassign)
messages/Ticket.go:78:5:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:94:19:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:95:14:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:96:17:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:97:17:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:98:19:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:114:17:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:142:2:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:143:2:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:144:2:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:145:2:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:146:2:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:147:2:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:161:2:warning: ineffectual assignment to err (ineffassign)
pac/kerb_validation_info.go:162:2:warning: ineffectual assignment to err (ineffassign)
```

### CODE REVIEW

**Comment by jcmturner** [comment]
Thanks for this. I may update some to used krberror.

**Comment by knweiss** [comment]
FYI: There are still 15 remaining `ineffassign` warnings in the tests that I did not fix. I wasn't sure if you would accept those fixes as there are also several other cases in the tests where `error` is assigned to `_` i.e. ignored (probably to keep the test code small).

**Comment by jcmturner** [comment]
Post the output here and I'll take a look. I may look to add gometalinter to my travis build to catch this stuff.

**Comment by knweiss** [comment]
Here's the list:
```
client/client_ad_integration_test.go:17:5:warning: ineffectual assignment to err (ineffassign)
client/client_ad_integration_test.go:31:5:warning: ineffectual assignment to err (ineffassign)
client/client_ad_integration_test.go:52:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:24:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:68:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:87:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:161:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:179:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:197:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:216:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:230:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:263:5:warning: ineffectual assignment to err (ineffassign)
client/client_integration_test.go:433:2:warning: ineffectual assignment to count (ineffassign)
client/client_integration_test.go:451:5:warning: ineffectual assignment to err (ineffassign)
gssapi/krb5Token_test.go:89:6:warning: ineffectual assignment to err (ineffassign)
```
A similar issue is
```
crypto/rfc4757/checksum.go:15::warning: Errors unhandled.,LOW,HIGH (gas)
```

Adding gometalinter to travis would be great (it still reports several other issues). It also helps to keep the Go code idiomatic.

(FWIW: It also reports the golint warning `warning: error strings should not be capitalized or end with punctuation or a newline`. My commits used capitalized error strings because I assumed you would prefer a consistent style over the golint recommendation.)

**Pull request merged**
