### PR TITLE
service: Respect RequiredHostAddr when ticket contains client addresses

### PR DESCRIPTION
**Pull request by dlespiau**
When the KDC is configured with noaddresses=false, the ticket will contain
client addresses it was issued for.

We still want to be able to disable the check on the service side though. It's
not unsual that the client address can't really be checked against, .eg SNAT
will effectly hide the client address we want to verify.

This commit changes the current behaviour: if the ticket contains client
addresses but RequireHostAddr is false (which is the default value),
ValidateAPREQ will now pass (it used to error out). The library user has to
explictly set RequireHostAddr to true for that check to happen.

### CODE REVIEW

**Comment by dlespiau** [comment]
To be a bit clearer, the issue encountered here was KDC configured with `noaddresses = false` but the server had  no way to obtain the client address and validateAPREQ() would fail.

With the commit as-is, we loose the ability to automatically check the client address if the ticket contains them. We may want a second bool to control the validation behaviour better, eg.

```
- sa.Config.RequireHostAddr - If the ticket has no client address, fail the validation
- sa.Config.IgnoreHostAddr - whether the ticket has client addresses or not, don't check client addresses
```

**Comment by jcmturner** [comment]
I'm not sure this is the right way forward. Can I clarify a few things.

You say that the "KDC configured with ``noaddresses = false``" however this is a krb5.conf entry not a kdc.conf entry. Therefore I'm assuming that your clients are configured with this rather than the KDC. In which case can this client config be updated? If this is not possible there is the ``extra_addresses`` configuration whose purpose is to support NAT with ``noaddresses = false``:

> This allows a computer to use multiple local addresses, in order to allow Kerberos to work in a network that uses NATs while still using address-restricted tickets. The addresses should be in a comma-separated list. This option has no effect if noaddresses is true.

**Comment by dlespiau** [comment]
1. Yes, sorry, indeed that's a client setting
2. Unfortunately, no, the client config cannot be updated
3. I think the proposed patch isn't the right way forward either! What I really want is a parameter for the service to no honour these addresses during validation. Now of course this option would be off by default.
4. There are some signs that people want that elsewhere, say the `KdcDontCheckAddresses` in the [windows KDC](https://support.microsoft.com/en-gb/help/837361/kerberos-protocol-registry-entries-and-kdc-configuration-keys) (this is not strictly the same as I'm taking about the service validation, not KDC).

I can be a bit more verbose about the reasons I'm seeing this as a problem. We've built a Kerberos authentication module for Kubernetes. The authentication flow is not directly from a client to a service but it has to go through one extra hop in the middle:

```
                         encapsulated AP_REQ                             encapsulated AP_REQ
kerberos client -----------------------------------> api server ------------------------------------> kerberos service
```

the `api server` is a separate process running on its own machine, so the client IPs the `kerberos service` sees are the ones from `api server` not from the client directly. 

I see two solutions:
1. I find a way to get the `api server` to forward the client IP through so the service can check that
2. `sa.Config.IgnoreHostAddr` bool that the service can configure the validation check with to ignore that code path

**Comment by dlespiau** [comment]
Fair enough, I can see how providing such an option may not be desirable. I'll have a look at proxiable tickets, thanks for the pointer!

Tanks, Let's close this PR then!

**Pull request closed without merging**
