### PR TITLE
SPNEGO ticket reuse for HTTP client

### PR DESCRIPTION
**Pull request by L11R**
Relogin only if there is ticket for this SPN.

### CODE REVIEW

**Comment by L11R** [comment]
@jcmturner can someone review it and probably propose more proper fix? I guess it's important problem if library is used as client.

**Comment by L11R** [comment]
After testing this patch in live environment, I could call it successfull. We didn't DDoS our domain controller by requesting tons of tickets anymore. But it still would be cool someone (@jcmturner, @tyrannosaurus-becks?) will review the patch.

**Comment by jcmturner** [comment]
Hi there. Thanks for the contribution. 

Can I clarify something... Is the issue here that the login to get the TGT was putting unnecessary load on the KDC or was it the act of getting tickets to the service the client wants to access?

If the former then it may be best to handle this around where this code is in the ``Login()`` function of the client.
https://github.com/jcmturner/gokrb5/blob/aa384b608ee82fca13e4ea864af4f5769a348830/client/client.go#L169-L177

If the later then we need to bear in mind that the service (if implemented properly) should see this as a replay attack and not accept the same ticket twice.

Given there is some discussion to be had on the aim and the best way to implement this I suggest we continue on an issue. I have raised #351 for us to have this discussion assuming that it is about re-using the TGT and not re-using the service ticket.

Thanks!

**Comment by L11R** [comment]
@jcmturner
> Is the issue here that the login to get the TGT was putting unnecessary load on the KDC

This one. I use your library to create `cntlm` utility but for Kerberos. It worked for the first time, but after some surfing and testing I had got a ban from KDC, it stopped to respond in my case. After my patch client reuse tickets and works as should.

**Comment by jcmturner** [comment]
@L11R, thanks for the contribution. I'm closing this PR as I have addressed this in this commit: https://github.com/jcmturner/gokrb5/commit/f6bfec3ea4eca67c033019f15f7fa92ee589fdf7

**Comment by L11R** [comment]
@jcmturner cool, thanks!

**Comment by L11R** [comment]
@jcmturner as far as got it, this commit was in the branch that you deleted already :( I don't see it in newly released v8.

**Pull request closed without merging**
