### PR TITLE
Add conversion of keytabs back to byte array

### PR DESCRIPTION
**Pull request by jasonwbarnett**
I need this so I can modify keytabs using this library and then save them back to disk.

### CODE REVIEW

**Comment by jcmturner** [comment]
Thanks for the contribution. Because this would be a core library used in other applications I want to avoid dependencies other than the Go standard library as issues with the dependency could have large knock on effects. Would you consider committing something that did not depend on github.com/zhuangsirui/binpacker ?

I need to write contributing guidelines but I've not had time yet.

**Comment by jasonwbarnett** [comment]
Totally makes sense. What about replacing your unpacking/packing with this library and effectively just copying it into the project?

If you're down with that I would be happy to refactor for you.

**Comment by jasonwbarnett** [comment]
Submitted PR to import binpacker. License is MIT, so seems to be reasonable approach. Once #79 is merged and you tag it v2.2.0, I can update #77 to use that instead.

Let me know if you're against doing this altogether.

**Comment by jcmturner** [comment]
I've merged in an update the enables you to marshal the Keytab to []bytes and a method to write to an io.Writer.

I think this should suit your needs without depending on a third party package so I'm closing this PR.

**Pull request closed without merging**
